# Generated by Django 4.2 on 2024-01-28 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklist', '0003_rename_comment_comment_parent_comment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
